---
- name: New AWS Provisioning Workflow
  hosts: localhost
  tasks:
    - name: Deploy the PostgreSQL DB
      ansible.builtin.debug:
        msg: |
          Deploying the PostgreSQL DB with Lamna Standards to RHEL Server

    - name: Waiting for completion
      ansible.builtin.pause:
        seconds: 3
        prompt: ""
        echo: false

    - name: Deploy the PostgreSQL DB...complete
      ansible.builtin.debug:
        msg: |
          Deploying the PostgreSQL DB with Lamna Standards to RHEL Server...completed

# ----------------------------------------

    - name: Apply the PostgreSQL DB settings
      ansible.builtin.debug:
        msg: |
          Applying the PostgreSQL DB settings

    - name: Waiting for complettion
      ansible.builtin.pause:
        seconds: 3
        prompt: ""
        echo: false

    - name: Apply the PostgreSQL DB settings...complete
      ansible.builtin.debug:
        msg: |
          Settings applied successfully to the PostgreSQL DB
