---
- name: New AWS Provisioning Workflow
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy the PostgreSQL DB
      ansible.builtin.debug:
        msg: |
          Deploying the PostgreSQL DB with Lamna Standards to RHEL Server

    - name: Waiting for completion-bad1
      no_log: true
      ansible.builtin.pause:
        seconds: 3
        prompt: ""

    - name: Deploy the PostgreSQL DB...complete
      ansible.builtin.debug:
        msg: |
          Deploying the PostgreSQL DB with Lamna Standards to RHEL Server...completed

# ----------------------------------------

    - name: Apply the PostgreSQL DB settings
      ansible.builtin.debug:
        msg: |
          Applying the PostgreSQL DB settings

    - name: Waiting for completion-bad2
      no_log: true
      ansible.builtin.pause:
        seconds: 3
        prompt: ""

    - name: Waiting for completion
      ansible.builtin.command: sleep 3
      changed_when: false
      no_log: true


    - name: Apply the PostgreSQL DB settings...complete
      ansible.builtin.debug:
        msg: |
          Settings applied successfully to the PostgreSQL DB
