---
- name: setup azure demo LAMNA HEALTHCARE ENVIRONMENT
  hosts: localhost
  gather_facts: false
  become: true

  tasks:

    - name: Add project
      ansible.controller.project:
        name: "LAMNA HealthCare Project"
        description: "This is from github.com/HichamMourad/lamna_fulldevenv"
        organization: "Default"
        state: present
        scm_type: git
        scm_url: https://github.com/HichamMourad/lamna_fulldevenv.git
        default_environment: "ee-cloud-services"

    - name: create the job templates needed for the Workflow
      ansible.controller.job_template:
        name: "{{ item.name }}"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        project: "LAMNA HealthCare Project"
        playbook: "{{ item.playbook }}"
        credentials:
          - "This AAPs Credentials controller.aapmerzlmeth7jle.az.ansiblecloud.com"
        state: "present"
      with_items:
        - { playbook: 'config_azure_dbsvcs.yml', name: 'L Config Azure DB Services' }
        - { playbook: 'deploy_azure_dbsvcs.yml', name: 'L Deploy Azure DB Services' }
        - { playbook: 'config_mgmt-rhel.yml', name: 'L Config MGMT for RHEL' }
        - { playbook: 'spin_up_rhel8.yml', name: 'L Deploy RHEL Servers' }
        - { playbook: 'spin_up_rhel8.yml', name: 'L Deploy Windows Servers' }
        - { playbook: 'config_mgmt-windows.yml', name: 'L Config MGMT Windows Servers' }
        - { playbook: 'deploy-containers-aks.yml', name: 'L Deploy AKS Containers' }        
        - { playbook: 'deploy_iis_webservers.yml', name: 'L Deploy IIS Web Servers' }
        - { playbook: 'notify_ms_teams.yml', name: 'L Notify MS Teams' }
        - { playbook: 'sn_create_change_request.yml', name: 'Create SN Change Request' }
        - { playbook: 'sn_update_change_request.yml', name: 'Update SN Change Request' }

    - name: create the workflow template and its schema
      ansible.controller.workflow_job_template:
        name: "L-WF Full Lamna Dev Environment"
        organization: "Default"
        schema:
        - identifier: "Create SN Change Request"
          unified_job_template:
            name: "Create SN Change Request"
            organization:
              name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "L Deploy RHEL Servers"
              - identifier: "L Deploy Windows Servers"
              - identifier: "L Deploy Azure DB Services"
              - identifier: "L Deploy AKS Containers"              
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "L Deploy RHEL Servers"
          unified_job_template:
            name: "L Deploy RHEL Servers"
            organization:
              name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "L Config MGMT for RHEL"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "L Config MGMT for RHEL"
          unified_job_template:
            name: "L Config MGMT for RHEL"
            organization:
              name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "L Notify MS Teams"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "L Deploy Windows Servers"
          unified_job_template:
            name: "L Deploy Windows Servers"
            organization:
              name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "L Config MGMT Windows Servers"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "L Config MGMT Windows Servers"
          unified_job_template:
            name: "L Config MGMT Windows Servers"
            organization:
              name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "L Deploy IIS Web Servers"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "L Deploy IIS Web Servers"
          unified_job_template:
            name: "L Deploy IIS Web Servers"
            organization:
              name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "L Notify MS Teams"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "L Deploy Azure DB Services"
          unified_job_template:
            name: "L Deploy Azure DB Services"
            organization:
              name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "L Config Azure DB Services"
            failure_nodes: []
            always_nodes: []
            credentials: []

        - identifier: "L Config Azure DB Services"
          unified_job_template:
            name: "L Config Azure DB Services"
            organization:
              name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "L Notify MS Teams"
            failure_nodes: []
            always_nodes: []
            credentials: []
 
        - identifier: "L Deploy AKS Containers"
          unified_job_template:
            name: "L Deploy AKS Containers"
            organization:
              name: "Default"
            type: job_template
          related:
            success_nodes:
              - identifier: "L Notify MS Teams"
              - identifier: "Update SN Change Request"
            failure_nodes: []
            always_nodes: []
            credentials: []

        # - identifier: "Update SN Change Request"
        #   unified_job_template:
        #     name: "Update SN Change Request"
        #     organization:
        #       name: "Default"
        #     type: job_template
        #   related:
        #     success_nodes: []
        #     failure_nodes: []
        #     always_nodes: []
        #     credentials: []

        # - identifier: "L Notify MS Teams"
        #   unified_job_template:
        #     name: "L Notify MS Teams"
        #     organization:
        #       name: "Default"
        #     type: job_template
        #   related:
        #     success_nodes: []
        #     failure_nodes: []
        #     always_nodes: []
        #     credentials: []
