---
- name: Update ServiceNow Change Request
  hosts: localhost
  tasks:
    - name: Updating ServiceNow Change Request
      ansible.builtin.debug:
        msg: "Updating ServiceNow Change Request..."

    - name: Waiting
      ansible.builtin.pause:
        seconds: 18
        prompt: "ServiceNow Change Request was UPDATED successfully!"
