- name: Deploy the Lamna Windows 2022 servers
  hosts: localhost
  tasks:
    - name: Deploy the Lamna Windows 2022 servers
      debug:
        msg: "Deploying the Windows 2022 servers with Lamna Standards for Windows 2022 Servers..."

    - pause:
        seconds: 23
        prompt: "Windows 2022 Servers deployment is complete!"
